# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  A study of the three major concepts of a modern operating systems: virtualization, 
  concurrency and persistence. Topics include the memory hierarchy (including caching and 
  virtual memory), memory managment, processes, processor scheduling, address spaces, 
  threads, the critical section problem, locks, sockets, file systems, and system performance 
  analysis.
baseurl: "/csci320" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

number: CSCI 320
title: Operating Systems & Concurrency
semester: Spring 2021

navigation:
  - title: Overview
    subfolderitems:
      - page: Description
        url: '#description'
      - page: Learning Goals
        url: '#goals'
      - page: Resources
        url: '#resources'
  - page: Calendar
    url: '#calendar'
  - title: Assessment
    subfolderitems:
    - page: Projects
      url: '#projects'
    - page: Final Project
      url: '#finalproject'
    - page: Participation
      url: '#participation'
    - page: Specifications Grading
      url: '#grading'
    - page: Late Days
      url: '#latedays'
  - page: Commitments
    url: '#commitments'

instructors:
  - id: ferrer
    name: Dr. Gabriel Ferrer
    email: ferrer@hendrix.edu
    web: http://ozark.hendrix.edu/~ferrer
    phone: (501) 450-3879
    officehours: https://drferrer.youcanbook.me/

offerings:
  - name: LECTURE 01
    loc: MCREY 315
    time: MWF 8:10am - 9:00am
    instructor: ferrer

resources:
  - name: Operating Systems Three Easy Pieces
    image: assets/images/15gjeeky-front-shortedge-384.jpg
    url: http://pages.cs.wisc.edu/~remzi/OSTEP/
  - name: Rust Programming Language
    image: assets/images/rust-logo-blk.svg
    url: https://www.rust-lang.org/
  - name: The Rust Book
    image: assets/images/Rust2018_front.webp
    url: https://doc.rust-lang.org/book/
  - name: Writing an OS in Rust
    image: assets/images/241211.png
    url: https://os.phil-opp.com/

extra-resources:
  - name: "How to Think Like a Computer Scientist: Interactive Edition"
    image: assets/images/runestone_logo.png
    url: https://runestone.academy/runestone/books/published/thinkcspy/index.html
  - name: Python Tutor
    image: assets/images/python_tutor.png
    url: http://pythontutor.com/
  - name: CodingBat Python
    image: assets/images/codingbat.jpg
    url: https://codingbat.com/python
  - name: CheckiO Python Practice
    image: assets/images/checkio_logo_small.png
    url: https://py.checkio.org/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
